---
language: ruby
bundler_args: --without development system_tests
before_install:
  - rm Gemfile.lock || true
  - gem update --system
script: 'bundle exec rake $CHECK'
matrix:
  include:
  - rvm: 1.9.3
    env: PUPPET_VERSION="~> 3.0" STRICT_VARIABLES=yes FUTURE_PARSER=yes CHECK=test
  - rvm: 2.1.9
    env: PUPPET_VERSION="~> 3.0" STRICT_VARIABLES=yes CHECK=test
  - rvm: 2.1.9
    env: PUPPET_VERSION="~> 4.0" STRICT_VARIABLES=yes CHECK=test
  - rvm: 2.2.6
    env: PUPPET_VERSION="~> 4.0" STRICT_VARIABLES=yes CHECK=test
  - rvm: 2.3.3
    env: PUPPET_VERSION="~> 4.0" STRICT_VARIABLES=yes CHECK=test
  - rvm: 2.3.3
    env: PUPPET_VERSION="~> 4.0" STRICT_VARIABLES=yes CHECK=rubocop
